/* eslint-disable import/prefer-default-export */
export const tableHead = [
  '_id',
  'createdAt',
  'name',
  'username',
  'email',
  'action',
];

export const patients = [
  {
    id: 1,
    firstName: 'Alice',
    lastName: 'Johnson',
    location: 'New York',
    email: 'alice.johnson@example.com',
    mobileNumber: '+1 (555) 123-4567',
    reason: 'Appointment scheduling',
  },
  {
    id: 2,
    firstName: 'Bob',
    lastName: 'Smith',
    location: 'Los Angeles',
    email: 'bob.smith@example.com',
    mobileNumber: '+1 (555) 234-5678',
    reason: 'Product inquiry',
  },
  {
    id: 3,
    firstName: 'Charlie',
    lastName: 'Brown',
    location: 'Chicago',
    email: 'charlie.brown@example.com',
    mobileNumber: '+1 (555) 345-6789',
    reason: 'Service complaint',
  },
  {
    id: 4,
    firstName: 'Diana',
    lastName: 'Taylor',
    location: 'Houston',
    email: 'diana.taylor@example.com',
    mobileNumber: '+1 (555) 456-7890',
    reason: 'Feedback submission',
  },
  {
    id: 5,
    firstName: 'Eleanor',
    lastName: 'Clark',
    location: 'Miami',
    email: 'eleanor.clark@example.com',
    mobileNumber: '+1 (555) 567-8901',
    reason: 'Appointment rescheduling',
  },
  {
    id: 6,
    firstName: 'Frank',
    lastName: 'White',
    location: 'Seattle',
    email: 'frank.white@example.com',
    mobileNumber: '+1 (555) 678-9012',
    reason: 'General inquiry',
  },
  {
    id: 7,
    firstName: 'Grace',
    lastName: 'Martinez',
    location: 'San Francisco',
    email: 'grace.martinez@example.com',
    mobileNumber: '+1 (555) 789-0123',
    reason: 'Technical support',
  },
  {
    id: 8,
    firstName: 'Henry',
    lastName: 'Miller',
    location: 'Boston',
    email: 'henry.miller@example.com',
    mobileNumber: '+1 (555) 890-1234',
    reason: 'Billing issue',
  },
  {
    id: 9,
    firstName: 'Ivy',
    lastName: 'Lee',
    location: 'Washington, D.C.',
    email: 'ivy.lee@example.com',
    mobileNumber: '+1 (555) 901-2345',
    reason: 'Account activation',
  },
  {
    id: 10,
    firstName: 'Jack',
    lastName: 'Brown',
    location: 'Dallas',
    email: 'jack.brown@example.com',
    mobileNumber: '+1 (555) 012-3456',
    reason: 'Complaint resolution',
  },
];
